# 应用服务 WEB 访问端口
server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-verificationcode
logging:
  config: classpath:logback.xml

