server:
  port: 8085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-map
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
logging:
  config: classpath:logback.xml

#自定义的key:value
amap:
  key: 7a90a823f2e7245d276028af9f4e76dd
